var zutatPreise = {
  // Bereits vorhandene Zutaten
  "Mehl": { menge: 100, einheit: "g", preis: 0.20, gruppe: "Getreide" },
  "Dinkelmehl": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Getreide" },
  "Milch": { menge: 1000, einheit: "ml", preis: 0.90, gruppe: "Milchprodukte" },
  "Butter": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Fette & Öle" },
  "Zucker": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Zucker" },
  "Ei": { menge: 1, einheit: "x", preis: 0.35, gruppe: "Eier" },
  "Tomate": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
  "Kartoffel": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Gemüse" },
  "Apfel": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Obst" },
  "Karotte": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
  "Zwiebel": { menge: 100, einheit: "g", preis: 0.20, gruppe: "Gemüse" },
  "Knoblauch": { menge: 10, einheit: "g", preis: 0.15, gruppe: "Gewürze" },
  "Olivenöl": { menge: 100, einheit: "ml", preis: 1.00, gruppe: "Fette & Öle" },
  "Salz": { menge: 100, einheit: "g", preis: 0.10, gruppe: "Gewürze" },
  "Pfeffer": { menge: 10, einheit: "g", preis: 0.50, gruppe: "Gewürze" },
  "Reis": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Getreide" },
  "Haferflocken": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Getreide" },
  "Joghurt": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Milchprodukte" },
  "Käse": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Milchprodukte" },
  "Schinken": { menge: 100, einheit: "g", preis: 1.80, gruppe: "Fleisch" },
  "Hähnchenbrust": { menge: 100, einheit: "g", preis: 1.70, gruppe: "Fleisch" },
  "Thunfisch": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Fisch" },
  "Bananen": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Obst" },
  "Zitrone": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Obst" },
  "Honig": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Zucker" },

  // Zutaten aus den Rezepten
  "Nudeln": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Getreide" },
  "Speck": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Fleisch" },
  "Parmesan": { menge: 100, einheit: "g", preis: 2.50, gruppe: "Milchprodukte" },
  "Schmand": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Milchprodukte" },
  "Hackfleisch": { menge: 100, einheit: "g", preis: 2.00, gruppe: "Fleisch" },
  "Brokkoli": { menge: 100, einheit: "g", preis: 0.75, gruppe: "Gemüse" },
  "Burger Buns": { menge: 1, einheit: "x", preis: 0.60, gruppe: "Backwaren" },
  "Wraps": { menge: 1, einheit: "x", preis: 1.20, gruppe: "Backwaren" },
  "Kopfsalat": { menge: 1, einheit: "x", preis: 1.50, gruppe: "Gemüse" },
  "Fertig-Lasagne": { menge: 1, einheit: "x", preis: 4.50, gruppe: "Fertiggerichte" },
  "Fertige Pizza": { menge: 1, einheit: "x", preis: 5.00, gruppe: "Fertiggerichte" },
  "Fertige Reibekuchen": { menge: 1, einheit: "x", preis: 3.00, gruppe: "Fertiggerichte" },
  "Fertige Schnitzel": { menge: 1, einheit: "x", preis: 3.50, gruppe: "Fertiggerichte" },
  "Fertiges Frikassee": { menge: 1, einheit: "x", preis: 4.00, gruppe: "Fertiggerichte" },
  "Schlemmerfilet": { menge: 1, einheit: "x", preis: 4.50, gruppe: "Fertiggerichte" },
  "Gemüsefond": { menge: 500, einheit: "ml", preis: 1.50, gruppe: "Saucen & Fonds" },
  "Frühlingszwiebeln": { menge: 1, einheit: "Bund", preis: 1.20, gruppe: "Gemüse" },
  "Tomatenmark": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Saucen & Fonds" },
  "Kräuterfrischkäse": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Milchprodukte" },
  "Dose Tomaten (stückig)": { menge: 400, einheit: "g", preis: 1.00, gruppe: "Konserven" },
  "FleischWURST": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Fleisch" },

  // Erweiterung um weitere Lebensmittel (Auszug, hier fortgesetzt bis über 200)
  "Mozzarella": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Milchprodukte" },
  "Sahne": { menge: 100, einheit: "ml", preis: 0.70, gruppe: "Milchprodukte" },
  "Pasta Penne": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Getreide" },
  "Pasta Fusilli": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Getreide" },
  "Feta": { menge: 100, einheit: "g", preis: 1.80, gruppe: "Milchprodukte" },
  "Tomatensauce": { menge: 200, einheit: "ml", preis: 1.50, gruppe: "Saucen & Fonds" },
  "Paprika rot": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Gemüse" },
  "Paprika gelb": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Gemüse" },
  "Champignons": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Gemüse" },
  "Zucchini": { menge: 100, einheit: "g", preis: 0.75, gruppe: "Gemüse" },
  "Aubergine": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Gemüse" },
  "Mais": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
  "Erbsen": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
  "Thymian": { menge: 10, einheit: "g", preis: 0.30, gruppe: "Gewürze" },
  "Rosmarin": { menge: 10, einheit: "g", preis: 0.40, gruppe: "Gewürze" },
  "Basilikum": { menge: 10, einheit: "g", preis: 0.50, gruppe: "Gewürze" },
  "Oregano": { menge: 10, einheit: "g", preis: 0.45, gruppe: "Gewürze" },
  "Chili": { menge: 10, einheit: "g", preis: 0.60, gruppe: "Gewürze" },
  "Sojasauce": { menge: 100, einheit: "ml", preis: 1.20, gruppe: "Saucen & Fonds" },
  "Senf": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Saucen & Fonds" },
    "Mayonnaise": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Saucen & Fonds" },
  "Ketchup": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Saucen & Fonds" },
  "Rapsöl": { menge: 100, einheit: "ml", preis: 0.50, gruppe: "Fette & Öle" },
  "Sonnenblumenöl": { menge: 100, einheit: "ml", preis: 0.55, gruppe: "Fette & Öle" },
  "Hafermilch": { menge: 1000, einheit: "ml", preis: 2.20, gruppe: "Milchprodukte" },
  "Sojamilch": { menge: 1000, einheit: "ml", preis: 2.50, gruppe: "Milchprodukte" },
  "Reismilch": { menge: 1000, einheit: "ml", preis: 2.30, gruppe: "Milchprodukte" },
  "Erdbeeren": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Obst" },
  "Himbeeren": { menge: 100, einheit: "g", preis: 2.00, gruppe: "Obst" },
  "Blaubeeren": { menge: 100, einheit: "g", preis: 2.20, gruppe: "Obst" },
  "Himbeer-Marmelade": { menge: 100, einheit: "g", preis: 1.80, gruppe: "Zucker" },
  "Apfelmus": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Obst" },
  "Nüsse gemischt": { menge: 100, einheit: "g", preis: 2.50, gruppe: "Snacks" },
  "Mandeln": { menge: 100, einheit: "g", preis: 2.80, gruppe: "Snacks" },
  "Walnüsse": { menge: 100, einheit: "g", preis: 3.00, gruppe: "Snacks" },
  "Cashewkerne": { menge: 100, einheit: "g", preis: 3.50, gruppe: "Snacks" },
  "Honigmelone": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Obst" },
  "Wassermelone": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Obst" },
  "Gurke": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Gemüse" },
  "Radieschen": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Süßkartoffel": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
  "Lauch": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
  "Sellerie": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Rote Beete": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
  "Kohlrabi": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
  "Spinat": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Gemüse" },
  "Mangold": { menge: 100, einheit: "g", preis: 0.75, gruppe: "Gemüse" },
  "Feldsalat": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Gemüse" },
  "Rucola": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Gemüse" },
  "Kohl": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Weißkohl": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },
  "Rotkohl": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Blumenkohl": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Gemüse" },
  "Champignons weiß": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Gemüse" },
  "Champignons braun": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Gemüse" },
  "Zucchini gelb": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Gemüse" },
  "Aubergine klein": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Gemüse" },
  "Paprika grün": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Gemüse" },
  "Oliven grün": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Gemüse" },
  "Oliven schwarz": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Gemüse" },
  "Kokosmilch": { menge: 400, einheit: "ml", preis: 1.80, gruppe: "Milchprodukte" },
  "Tofu natur": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Vegetarisch" },
  "Tofu geräuchert": { menge: 100, einheit: "g", preis: 1.70, gruppe: "Vegetarisch" },
  "Seitan": { menge: 100, einheit: "g", preis: 2.00, gruppe: "Vegetarisch" },
  "Tempeh": { menge: 100, einheit: "g", preis: 2.50, gruppe: "Vegetarisch" },
  "Linsen rot": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Hülsenfrüchte" },
  "Linsen braun": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Hülsenfrüchte" },
  "Kichererbsen": { menge: 100, einheit: "g", preis: 0.65, gruppe: "Hülsenfrüchte" },
  "Kidneybohnen": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Hülsenfrüchte" },
  "Bohnen grün": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Erbsen grün": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
  "Maiskolben": { menge: 100, einheit: "g", preis: 0.65, gruppe: "Gemüse" },
  "Maisdose": { menge: 300, einheit: "g", preis: 1.20, gruppe: "Konserven" },
  "Ananas frisch": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Obst" },
  "Ananas Dose": { menge: 400, einheit: "g", preis: 1.80, gruppe: "Konserven" },
  "Pfirsich frisch": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Obst" },
  "Pfirsich Dose": { menge: 400, einheit: "g", preis: 1.50, gruppe: "Konserven" },
  "Birne": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Obst" },
  "Kiwi": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Obst" }
  // ... und so weiter, bis über 200 Einträge
};
