var zutatPreise = {
  // Basiszutaten (alle Preise für 100g/ml oder 1 Stück)
  "Mehl": { menge: 100, einheit: "g", preis: 0.08, gruppe: "Getreide" },
  "Dinkelmehl": { menge: 100, einheit: "g", preis: 0.12, gruppe: "Getreide" },
  "Milch": { menge: 100, einheit: "ml", preis: 0.08, gruppe: "Milchprodukte" },
  "Butter": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Fette & Öle" },
  "Zucker": { menge: 100, einheit: "g", preis: 0.15, gruppe: "Zucker" },
  "Eier": { menge: 1, einheit: "x", preis: 0.25, gruppe: "Eier" },
  "Tomaten": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Gemüse" },
  "Kartoffel": { menge: 100, einheit: "g", preis: 0.12, gruppe: "Gemüse" },
  "Apfel": { menge: 100, einheit: "g", preis: 0.20, gruppe: "Obst" },
  "Karotte": { menge: 100, einheit: "g", preis: 0.15, gruppe: "Gemüse" },
  "Zwiebeln": { menge: 100, einheit: "g", preis: 0.10, gruppe: "Gemüse" },
  "Brokkoli": { menge: 1, einheit: "x", preis: 1.30, gruppe: "Gemüse" },
  "Knoblauch": { menge: 10, einheit: "g", preis: 0.08, gruppe: "Gewürze" },
  "Olivenöl": { menge: 100, einheit: "ml", preis: 0.60, gruppe: "Fette & Öle" },
  "Rapsöl": { menge: 100, einheit: "ml", preis: 0.30, gruppe: "Fette & Öle" },
  "Sonnenblumenöl": { menge: 100, einheit: "ml", preis: 0.35, gruppe: "Fette & Öle" },
  "Salz": { menge: 100, einheit: "g", preis: 0.05, gruppe: "Gewürze" },
  "Pfeffer": { menge: 10, einheit: "g", preis: 0.15, gruppe: "Gewürze" },
  "Reis": { menge: 100, einheit: "g", preis: 0.15, gruppe: "Getreide" },
  "Haferflocken": { menge: 100, einheit: "g", preis: 0.15, gruppe: "Getreide" },
  "Joghurt": { menge: 100, einheit: "g", preis: 0.15, gruppe: "Milchprodukte" },
  "Käse": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Milchprodukte" },
  "Schinken": { menge: 100, einheit: "g", preis: 0.95, gruppe: "Fleisch" },
  "Hähnchen": { menge: 100, einheit: "g", preis: 1.15, gruppe: "Fleisch" },
  "Hähnchenbrust": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Fleisch" },
  "Thunfisch": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Fisch" },
  "Bananen": { menge: 100, einheit: "g", preis: 0.20, gruppe: "Obst" },
  "Zitrone": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Obst" },
  "Honig": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Zucker" },

  // Zutaten aus Rezepten
  "Nudeln": { menge: 100, einheit: "g", preis: 0.08, gruppe: "Getreide" },
  "Speck": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Fleisch" },
  "Parmesan": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Milchprodukte" },
  "Schmand": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Milchprodukte" },
  "Hackfleisch": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Fleisch" },
  "Brokkoli": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Burger Buns": { menge: 1, einheit: "x", preis: 0.40, gruppe: "Backwaren" },
  "Wraps": { menge: 1, einheit: "x", preis: 0.90, gruppe: "Backwaren" },
  "Kopfsalat": { menge: 1, einheit: "x", preis: 1.00, gruppe: "Gemüse" },
  "Fertig-Lasagne": { menge: 1, einheit: "x", preis: 3.00, gruppe: "Fertiggerichte" },
  "TK-Pizza": { menge: 1, einheit: "x", preis: 3.50, gruppe: "Fertiggerichte" },
  "Fertig Reibekuchen": { menge: 1, einheit: "x", preis: 2.50, gruppe: "Fertiggerichte" },
  "Fertig-Schnitzel": { menge: 1, einheit: "x", preis: 2.80, gruppe: "Fertiggerichte" },
  "Fertig-Frikassee": { menge: 1, einheit: "x", preis: 3.20, gruppe: "Fertiggerichte" },
  "Schlemmerfilet": { menge: 1, einheit: "x", preis: 3.50, gruppe: "Fertiggerichte" },
  "Gemüsefond": { menge: 100, einheit: "ml", preis: 0.20, gruppe: "Saucen & Fonds" },
  "Bund Frühlingszwiebeln": { menge: 1, einheit: "x", preis: 0.80, gruppe: "Gemüse" },
  "Tomatenmark": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Saucen & Fonds" },
  "Kräuterfrischkäse": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Milchprodukte" },
  "Dose Tomaten (stückig)": { menge: 1, einheit: "x", preis: 1.30, gruppe: "Konserven" },
  "FleischWURST": { menge: 1, einheit: "x", preis: 2.50, gruppe: "Fleisch" },
   "Paprika rot": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },
  "Paprika gelb": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },
  "Paprika grün": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },
  "Zucchini": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
  "Aubergine": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Gemüse" },
  "Brokkoli": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Blumenkohl": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },
  "Spinat": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
  "Mangold": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
  "Feldsalat": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Gemüse" },
  "Rucola": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Gemüse" },
  "Kohlrabi": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
  "Weißkohl": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Gemüse" },
  "Rotkohl": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
  "Sellerie": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
  "Lauch": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Gemüse" },
  "Süßkartoffel": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },
  "Gurke": { menge: 100, einheit: "g", preis: 0.20, gruppe: "Gemüse" },
  "Radieschen": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Gemüse" },
  "Bohnen grün": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Gemüse" },
  "Erbsen grün": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Gemüse" },
  "Maiskolben": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
  "Champignons weiß": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Gemüse" },
  "Champignons braun": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },

  // Obst
  "Erdbeeren": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Obst" },
  "Himbeeren": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Obst" },
  "Blaubeeren": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Obst" },
  "Himbeermarmelade": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Zucker" },
  "Apfelmus": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Obst" },
  "Honigmelone": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Obst" },
  "Wassermelone": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Obst" },
  "Ananas frisch": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Obst" },
  "Pfirsich frisch": { menge: 100, einheit: "g", preis: 0.65, gruppe: "Obst" },
  "Birne": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Obst" },
  "Kiwi": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Obst" },
  
  // Fleisch & Fisch
  "Rinderhack": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Fleisch" },
  "Putenbrust": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Fleisch" },
  "Lachs": { menge: 100, einheit: "g", preis: 1.80, gruppe: "Fisch" },
  "Forelle": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Fisch" },
  "Garnelen": { menge: 100, einheit: "g", preis: 2.50, gruppe: "Fisch" },

  // Hülsenfrüchte
  "Linsen rot": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Hülsenfrüchte" },
  "Linsen braun": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Hülsenfrüchte" },
  "Kichererbsen": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Hülsenfrüchte" },
  "Kidneybohnen": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Hülsenfrüchte" },

  // Snacks & Nüsse
  "Mandeln": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Snacks" },
  "Walnüsse": { menge: 100, einheit: "g", preis: 1.70, gruppe: "Snacks" },
  "Cashewkerne": { menge: 100, einheit: "g", preis: 1.80, gruppe: "Snacks" },
  "Haselnüsse": { menge: 100, einheit: "g", preis: 1.40, gruppe: "Snacks" },
  "Pistazien": { menge: 100, einheit: "g", preis: 2.00, gruppe: "Snacks" },

  // Saucen & Fonds
  "Tomatensauce": { menge: 100, einheit: "ml", preis: 0.50, gruppe: "Saucen & Fonds" },
  "Sojasauce": { menge: 100, einheit: "ml", preis: 0.60, gruppe: "Saucen & Fonds" },
  "Ketchup": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Saucen & Fonds" },
  "Mayonnaise": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Saucen & Fonds" },
  "Senf": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Saucen & Fonds" },

  // Milchprodukte
  "Mozzarella": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Milchprodukte" },
  "Sahne": { menge: 100, einheit: "ml", preis: 0.35, gruppe: "Milchprodukte" },
  "Feta": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Milchprodukte" },
  "Kräuterbutter": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Milchprodukte" },
  "Quark": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Milchprodukte" },
  // Gemüse
  "Chinakohl": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Gemüse" },
  "Pak Choi": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Gemüse" },
  "Rosenkohl": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },
  "Okraschoten": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
  "Artischocke": { menge: 100, einheit: "g", preis: 0.65, gruppe: "Gemüse" },
  "Grüne Bohnen": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
  "Gelbe Bohnen": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
  "Auberginen mini": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Zuckerschoten": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
  "Frühlingszwiebeln klein": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Gemüse" },

  // Obst
  "Pflaumen": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Obst" },
  "Mirabellen": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Obst" },
  "Stachelbeeren": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Obst" },
  "Johannisbeeren": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Obst" },
  "Heidelbeeren gefroren": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Obst" },
  "Himbeeren gefroren": { menge: 100, einheit: "g", preis: 0.65, gruppe: "Obst" },
  "Erdbeeren gefroren": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Obst" },
  "Brombeeren": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Obst" },
  "Kaki": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Obst" },
  "Granatapfel": { menge: 100, einheit: "g", preis: 0.75, gruppe: "Obst" },

  // Milchprodukte & Eier
  "Ziegenkäse": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Milchprodukte" },
  "Schafskäse": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Milchprodukte" },
  "Ricotta": { menge: 100, einheit: "g", preis: 0.95, gruppe: "Milchprodukte" },
  "Mascarpone": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Milchprodukte" },
  "Büffelmozzarella": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Milchprodukte" },
  "Eier Bio": { menge: 1, einheit: "x", preis: 0.35, gruppe: "Eier" },
  "Eier klein": { menge: 1, einheit: "x", preis: 0.20, gruppe: "Eier" },
  "Eier groß": { menge: 1, einheit: "x", preis: 0.25, gruppe: "Eier" },
  "Eier gekocht": { menge: 1, einheit: "x", preis: 0.30, gruppe: "Eier" },
  "Eier weichgekocht": { menge: 1, einheit: "x", preis: 0.28, gruppe: "Eier" },

  // Fleisch & Fisch
  "Rindergulasch": { menge: 100, einheit: "g", preis: 1.40, gruppe: "Fleisch" },
  "Rindersteak": { menge: 100, einheit: "g", preis: 1.90, gruppe: "Fleisch" },
  "Schweinebauch": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Fleisch" },
  "Hähnchenschenkel": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Fleisch" },
  "Hähnchenflügel": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Fleisch" },
  "Putenhack": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Fleisch" },
  "Thunfisch Dose": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Fisch" },
  "Sardinen": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Fisch" },
  "Hering": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Fisch" },
  "Makrele": { menge: 100, einheit: "g", preis: 0.65, gruppe: "Fisch" },

  // Hülsenfrüchte
  "Mungobohnen": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Hülsenfrüchte" },
  "Adzukibohnen": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Hülsenfrüchte" },
  "Schwarze Augenbohnen": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Hülsenfrüchte" },
  "Weiße Bohnen getrocknet": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Hülsenfrüchte" },
  "Rote Linsen": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Hülsenfrüchte" },
  "Grüne Linsen": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Hülsenfrüchte" },
  "Borlotti Bohnen": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Hülsenfrüchte" },
  "Kichererbsen getrocknet": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Hülsenfrüchte" },
  "Erbsen getrocknet": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Hülsenfrüchte" },
  "Kidneybohnen getrocknet": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Hülsenfrüchte" },

  // Nüsse & Samen
  "Leinsamen": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Snacks" },
  "Chiasamen": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Snacks" },
  "Sonnenblumenkerne": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Snacks" },
  "Kürbiskerne": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Snacks" },
  "Sesam": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Snacks" },
  "Pinienkerne": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Snacks" },
  "Haselnüsse geröstet": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Snacks" },
  "Erdnusskerne": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Snacks" },
  "Cashewkerne geröstet": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Snacks" },
  "Walnüsse geschält": { menge: 100, einheit: "g", preis: 1.30, gruppe: "Snacks" },
    "Brokkolini": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
  "Fenchel": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },
  "Sellerieknolle": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Gemüse" },
  "Pastinake": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
  "Topinambur": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
  "Wirsing": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Gemüse" },
  "Endivie": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Radicchio": { menge: 100, einheit: "g", preis: 0.65, gruppe: "Gemüse" },
  "Chicorée": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
  "Mairübe": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },

  // Obst (weiter)
  "Nektarine": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Obst" },
  "Clementine": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Obst" },
  "Mandarine": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Obst" },
  "Limette": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Obst" },
  "Pfirsichkern": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Obst" },
  "Kokos": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Obst" },
  "Granatapfelsaft": { menge: 100, einheit: "ml", preis: 0.50, gruppe: "Getränke" },
  "Apfelsaft": { menge: 100, einheit: "ml", preis: 0.20, gruppe: "Getränke" },
  "Orangensaft": { menge: 100, einheit: "ml", preis: 0.25, gruppe: "Getränke" },
  "Multivitaminsaft": { menge: 100, einheit: "ml", preis: 0.30, gruppe: "Getränke" },

  // Milchprodukte & Eier (weiter)
  "Butter light": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Fette & Öle" },
  "Margarine": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Fette & Öle" },
  "Schafsmilch": { menge: 100, einheit: "ml", preis: 0.55, gruppe: "Milchprodukte" },
  "Ziegenmilch": { menge: 100, einheit: "ml", preis: 0.60, gruppe: "Milchprodukte" },
  "Buttermilch": { menge: 100, einheit: "ml", preis: 0.25, gruppe: "Milchprodukte" },
  "Quark": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Milchprodukte" },
  "Magerquark": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Milchprodukte" },
  "Sahne light": { menge: 100, einheit: "ml", preis: 0.40, gruppe: "Milchprodukte" },
  "Crème fraîche": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Milchprodukte" },
  "Feta light": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Milchprodukte" },

  // Fleisch & Fisch (weiter)
  "Rinderhack": { menge: 100, einheit: "g", preis: 1.30, gruppe: "Fleisch" },
  "Schweinehack": { menge: 100, einheit: "g", preis: 1.00, gruppe: "Fleisch" },
  "Kalbsschnitzel": { menge: 100, einheit: "g", preis: 1.80, gruppe: "Fleisch" },
  "Rinderbraten": { menge: 100, einheit: "g", preis: 1.60, gruppe: "Fleisch" },
  "Lachs": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Fisch" },
  "Forelle": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Fisch" },
  "Seelachs": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Fisch" },
  "Scholle": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Fisch" },
  "Kabeljau": { menge: 100, einheit: "g", preis: 1.00, gruppe: "Fisch" },
  "Rotbarsch": { menge: 100, einheit: "g", preis: 0.95, gruppe: "Fisch" },

  // Hülsenfrüchte (weiter)
  "Lupinen": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Hülsenfrüchte" },
  "Sojabohnen getrocknet": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Hülsenfrüchte" },
  "Weiße Bohnen Dose": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Konserven" },
  "Rote Linsen Dose": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Konserven" },
  "Kichererbsen Dose": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Konserven" },
  "Kidneybohnen Dose": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Konserven" },
  "Erbsen Dose": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Konserven" },
  "Mais Dose": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Konserven" },
  "Tomaten Dose": { menge: 100, einheit: "g", preis: 0.20, gruppe: "Konserven" },
  "Bohnenmix Dose": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Konserven" },

  // Nüsse & Samen (weiter)
  "Haselnüsse ungeröstet": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Snacks" },
  "Mandeln ungeröstet": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Snacks" },
  "Walnüsse ungeröstet": { menge: 100, einheit: "g", preis: 1.25, gruppe: "Snacks" },
  "Erdnussbutter": { menge: 100, einheit: "g", preis: 0.65, gruppe: "Snacks" },
  "Mandelmus": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Snacks" },
  "Cashewmus": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Snacks" },
  "Tahini": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Snacks" },
  "Erdnüsse gesalzen": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Snacks" },
  "Pekanüsse": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Snacks" },
  "Macadamianüsse": { menge: 100, einheit: "g", preis: 1.80, gruppe: "Snacks" },
    "Kürbis Hokkaido": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Gemüse" },
  "Kürbis Butternut": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
  "Spargel grün": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
  "Spargel weiß": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Gemüse" },
  "Zuckerschoten": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Aubergine klein": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },
  "Paprika lila": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
  "Mangold bunt": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
  "Pak Choi": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
  "Chayote": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },

  // Obst
  "Heidelbeeren": { menge: 100, einheit: "g", preis: 0.95, gruppe: "Obst" },
  "Johannisbeeren rot": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Obst" },
  "Johannisbeeren schwarz": { menge: 100, einheit: "g", preis: 0.95, gruppe: "Obst" },
  "Stachelbeeren": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Obst" },
  "Preiselbeeren": { menge: 100, einheit: "g", preis: 0.75, gruppe: "Obst" },
  "Brombeeren": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Obst" },
  "Physalis": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Obst" },
  "Kaki": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Obst" },
  "Feigen frisch": { menge: 100, einheit: "g", preis: 0.75, gruppe: "Obst" },
  "Drachenfrucht": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Obst" },

  // Fleisch
  "Hähnchenschenkel": { menge: 100, einheit: "g", preis: 0.95, gruppe: "Fleisch" },
  "Hähnchenfilet": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Fleisch" },
  "Putenhack": { menge: 100, einheit: "g", preis: 1.25, gruppe: "Fleisch" },
  "Putenbrust": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Fleisch" },
  "Rinderfilet": { menge: 100, einheit: "g", preis: 2.00, gruppe: "Fleisch" },
  "Schweinekotelett": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Fleisch" },
  "Schweineschnitzel": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Fleisch" },
  "Speck gewürfelt": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Fleisch" },
  "Salami": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Fleisch" },
  "Mortadella": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Fleisch" },

  // Fisch
  "Makrele": { menge: 100, einheit: "g", preis: 0.75, gruppe: "Fisch" },
  "Hering": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Fisch" },
  "Sardinen": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Fisch" },
  "Garnelen": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Fisch" },
  "Tintenfisch": { menge: 100, einheit: "g", preis: 1.30, gruppe: "Fisch" },
  "Muscheln": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Fisch" },
  "Lachsfilet": { menge: 100, einheit: "g", preis: 1.60, gruppe: "Fisch" },
  "Thunfisch frisch": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Fisch" },
  "Forellenfilet": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Fisch" },
  "Kabeljaufilet": { menge: 100, einheit: "g", preis: 1.00, gruppe: "Fisch" },

  // Milchprodukte & Eier
  "Schlagsahne": { menge: 100, einheit: "ml", preis: 0.30, gruppe: "Milchprodukte" },
  "Kefir": { menge: 100, einheit: "ml", preis: 0.25, gruppe: "Milchprodukte" },
  "Hüttenkäse": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Milchprodukte" },
  "Ricotta": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Milchprodukte" },
  "Mascarpone": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Milchprodukte" },
  "Eier hart gekocht": { menge: 1, einheit: "x", preis: 0.25, gruppe: "Eier" },
  "Eier weich gekocht": { menge: 1, einheit: "x", preis: 0.25, gruppe: "Eier" },
  "Mozzarella mini": { menge: 100, einheit: "g", preis: 0.75, gruppe: "Milchprodukte" },
  "Büffelmozzarella": { menge: 100, einheit: "g", preis: 1.10, gruppe: "Milchprodukte" },
  "Emmentaler": { menge: 100, einheit: "g", preis: 0.95, gruppe: "Milchprodukte" },

  // Hülsenfrüchte & Nüsse
  "Sojabohnen": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Hülsenfrüchte" },
  "Linsen gelb": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Hülsenfrüchte" },
  "Linsen braun trocken": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Hülsenfrüchte" },
  "Erbsen grün trocken": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Hülsenfrüchte" },
  "Kichererbsen trocken": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Hülsenfrüchte" },
  "Kidneybohnen trocken": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Hülsenfrüchte" },
  "Buchweizen": { menge:100, einheit:"g", preis:0.40, gruppe:"Getreide" },
  "Quinoa": { menge:100, einheit:"g", preis:0.75, gruppe:"Getreide" },
  "Amaranth": { menge:100, einheit:"g", preis:0.65, gruppe:"Getreide" },
  "Haferkleie": { menge:100, einheit:"g", preis:0.35, gruppe:"Getreide" },

  // Backwaren & Getreide
  "Toastbrot": { menge: 1, einheit: "x", preis: 1.20, gruppe: "Backwaren" },
  "Vollkornbrot": { menge: 1, einheit: "x", preis: 1.50, gruppe: "Backwaren" },
  "Baguette": { menge: 1, einheit: "x", preis: 0.85, gruppe: "Backwaren" },
  "Ciabatta": { menge: 1, einheit: "x", preis: 1.00, gruppe: "Backwaren" },
  "Brötchen": { menge: 1, einheit: "x", preis: 0.25, gruppe: "Backwaren" },
  "Kaiserbrötchen": { menge: 1, einheit: "x", preis: 0.30, gruppe: "Backwaren" },
  "Croissant": { menge: 1, einheit: "x", preis: 0.40, gruppe: "Backwaren" },
  "Laugenbrezel": { menge: 1, einheit: "x", preis: 0.50, gruppe: "Backwaren" },
  "Vollkornbrötchen": { menge: 1, einheit: "x", preis: 0.35, gruppe: "Backwaren" },
  "Pita Brot": { menge: 1, einheit: "x", preis: 0.45, gruppe: "Backwaren" },
    "Chips Salz": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Snacks" },
  "Chips Paprika": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Snacks" },
  "Popcorn gesalzen": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Snacks" },
  "Popcorn süß": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Snacks" },
  "Kekse Butter": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Snacks" },
  "Kekse Schoko": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Snacks" },
  "Schokolade Vollmilch": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Snacks" },
  "Schokolade Zartbitter": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Snacks" },
  "Riegel Müsliriegel": { menge: 100, einheit: "g", preis: 0.95, gruppe: "Snacks" },
  "Riegel Schokoriegel": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Snacks" },

  // Getränke
  "Wasser still": { menge: 100, einheit: "ml", preis: 0.05, gruppe: "Getränke" },
  "Wasser Sprudel": { menge: 100, einheit: "ml", preis: 0.05, gruppe: "Getränke" },
  "Orangensaft": { menge: 100, einheit: "ml", preis: 0.20, gruppe: "Getränke" },
  "Apfelsaft": { menge: 100, einheit: "ml", preis: 0.18, gruppe: "Getränke" },
  "Multivitaminsaft": { menge: 100, einheit: "ml", preis: 0.25, gruppe: "Getränke" },
  "Cola": { menge: 100, einheit: "ml", preis: 0.15, gruppe: "Getränke" },
  "Limo": { menge: 100, einheit: "ml", preis: 0.15, gruppe: "Getränke" },
  "Tee schwarz": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Getränke" },
  "Tee grün": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Getränke" },
  "Kaffee gemahlen": { menge: 100, einheit: "g", preis: 0.70, gruppe: "Getränke" },

  // Saucen & Fonds
  "Ketchup": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Saucen & Fonds" },
  "Mayonnaise": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Saucen & Fonds" },
  "Senf mild": { menge: 100, einheit: "g", preis: 0.20, gruppe: "Saucen & Fonds" },
  "Senf scharf": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Saucen & Fonds" },
  "Sojasauce": { menge: 100, einheit: "ml", preis: 0.50, gruppe: "Saucen & Fonds" },
  "BBQ Sauce": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Saucen & Fonds" },
  "Chilisauce": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Saucen & Fonds" },
  "Currysauce": { menge: 100, einheit: "g", preis: 0.65, gruppe: "Saucen & Fonds" },
  "Tomatenketchup Bio": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Saucen & Fonds" },
  "Pesto grün": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Saucen & Fonds" },

  // Kräuter & Gewürze
  "Basilikum getrocknet": { menge: 10, einheit: "g", preis: 0.15, gruppe: "Gewürze" },
  "Oregano getrocknet": { menge: 10, einheit: "g", preis: 0.12, gruppe: "Gewürze" },
  "Thymian getrocknet": { menge: 10, einheit: "g", preis: 0.15, gruppe: "Gewürze" },
  "Rosmarin getrocknet": { menge: 10, einheit: "g", preis: 0.20, gruppe: "Gewürze" },
  "Petersilie frisch": { menge: 100, einheit: "g", preis: 0.25, gruppe: "Gewürze" },
  "Schnittlauch frisch": { menge: 100, einheit: "g", preis: 0.30, gruppe: "Gewürze" },
  "Koriander frisch": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Gewürze" },
  "Paprikapulver edelsüß": { menge: 10, einheit: "g", preis: 0.10, gruppe: "Gewürze" },
  "Paprikapulver scharf": { menge: 10, einheit: "g", preis: 0.12, gruppe: "Gewürze" },
  "Chilipulver": { menge: 10, einheit: "g", preis: 0.15, gruppe: "Gewürze" },

  // Vegane / vegetarische Produkte
  "Tofu natur": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Vegetarisch" },
  "Tofu geräuchert": { menge: 100, einheit: "g", preis: 0.75, gruppe: "Vegetarisch" },
  "Tempeh": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Vegetarisch" },
  "Seitan": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Vegetarisch" },
  "Vegane Burger Patties": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Vegetarisch" },
  "Vegane Würstchen": { menge: 100, einheit: "g", preis: 0.95, gruppe: "Vegetarisch" },
  "Haferdrink": { menge: 100, einheit: "ml", preis: 0.10, gruppe: "Milchprodukte" },
  "Sojadrink": { menge: 100, einheit: "ml", preis: 0.12, gruppe: "Milchprodukte" },
  "Mandelmilch": { menge: 100, einheit: "ml", preis: 0.15, gruppe: "Milchprodukte" },
  "Reismilch": { menge: 100, einheit: "ml", preis: 0.12, gruppe: "Milchprodukte" },
  "Okra": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
"Yams": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
"Rettich": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
"Schwarzwurzel": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
"Topinambur Knolle": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Gemüse" },
"Meerrettich": { menge: 100, einheit: "g", preis: 0.45, gruppe: "Gemüse" },
"Chinakohl baby": { menge: 100, einheit: "g", preis: 0.35, gruppe: "Gemüse" },
"Rübstiel": { menge: 100, einheit: "g", preis: 0.50, gruppe: "Gemüse" },
"Winterrettich": { menge: 100, einheit: "g", preis: 0.40, gruppe: "Gemüse" },
"Schwarzkohl": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Gemüse" },
"Passionsfrucht": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Obst" },
"Johannisbeeren weiß": { menge: 100, einheit: "g", preis: 1.00, gruppe: "Obst" },
"Goji Beeren": { menge: 100, einheit: "g", preis: 2.00, gruppe: "Obst" },
"Maulbeeren": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Obst" },
"Physalis getrocknet": { menge: 100, einheit: "g", preis: 1.80, gruppe: "Obst" },
"Sanddorn": { menge: 100, einheit: "g", preis: 1.60, gruppe: "Obst" },
"Mirabelle getrocknet": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Obst" },
"Quitte": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Obst" },
"Holunderbeeren": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Obst" },
"Maulbeeren getrocknet": { menge: 100, einheit: "g", preis: 1.90, gruppe: "Obst" },
"Wildschwein": { menge: 100, einheit: "g", preis: 2.50, gruppe: "Fleisch" },
"Reh": { menge: 100, einheit: "g", preis: 2.80, gruppe: "Fleisch" },
"Wildente": { menge: 100, einheit: "g", preis: 2.20, gruppe: "Fleisch" },
"Taube": { menge: 100, einheit: "g", preis: 2.10, gruppe: "Fleisch" },
"Tintenfisch Ringe": { menge: 100, einheit: "g", preis: 1.40, gruppe: "Fisch" },
"Jakobsmuschel": { menge: 100, einheit: "g", preis: 2.50, gruppe: "Fisch" },
"Seezunge": { menge: 100, einheit: "g", preis: 2.20, gruppe: "Fisch" },
"Steinbutt": { menge: 100, einheit: "g", preis: 2.80, gruppe: "Fisch" },
"Octopus": { menge: 100, einheit: "g", preis: 2.60, gruppe: "Fisch" },
"Barramundi": { menge: 100, einheit: "g", preis: 2.50, gruppe: "Fisch" },
"Schwarze Linsen": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Hülsenfrüchte" },
"Belugalinsen": { menge: 100, einheit: "g", preis: 1.00, gruppe: "Hülsenfrüchte" },
"Rote Kidneybohnen": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Hülsenfrüchte" },
"Adzukibohnen rot": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Hülsenfrüchte" },
"Hanfsamen": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Snacks" },
"Mohnsamen": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Snacks" },
"Kamut": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Getreide" },
"Teff": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Getreide" },
"Chlorella Pulver": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Snacks" },
"Spirulina Pulver": { menge: 100, einheit: "g", preis: 1.60, gruppe: "Snacks" },
"Schwarze Linsen": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Hülsenfrüchte" },
"Belugalinsen": { menge: 100, einheit: "g", preis: 1.00, gruppe: "Hülsenfrüchte" },
"Rote Kidneybohnen": { menge: 100, einheit: "g", preis: 0.55, gruppe: "Hülsenfrüchte" },
"Adzukibohnen rot": { menge: 100, einheit: "g", preis: 0.60, gruppe: "Hülsenfrüchte" },
"Hanfsamen": { menge: 100, einheit: "g", preis: 1.20, gruppe: "Snacks" },
"Mohnsamen": { menge: 100, einheit: "g", preis: 0.90, gruppe: "Snacks" },
"Kamut": { menge: 100, einheit: "g", preis: 0.85, gruppe: "Getreide" },
"Teff": { menge: 100, einheit: "g", preis: 0.80, gruppe: "Getreide" },
"Chlorella Pulver": { menge: 100, einheit: "g", preis: 1.50, gruppe: "Snacks" },
"Spirulina Pulver": { menge: 100, einheit: "g", preis: 1.60, gruppe: "Snacks" }
};
